In [1]:
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False
%config SqlMagic.displaylimit = 5
%config SqlMagic.named_parameters = "enabled"

In [2]:
import duckdb
import pandas as pd

%load_ext sql
conn = duckdb.connect()
%sql conn --alias duckdb

Tip: You may define configurations in /Users/i.korsakov/_code/github/everything_about_DuckDB/pyproject.toml or /Users/i.korsakov/.jupysql/config.

Did not find user configurations in /Users/i.korsakov/_code/github/everything_about_DuckDB/pyproject.toml.

In [3]:
%sql duckdb:///:memory:

In [4]:
%%sql
INSTALL httpfs;
LOAD httpfs;
SET s3_endpoint = 'localhost:9000';
SET s3_use_ssl = false;
SET s3_url_style = 'path';
SET s3_access_key_id = 'minioadmin';
SET s3_secret_access_key = 'minioadmin';

Empty DataFrame
Columns: [Success]
Index: []

In [5]:
%%sql
SELECT
    date_trunc('year', tpep_pickup_datetime) AS pickup_year,
    date_trunc('month', tpep_pickup_datetime) AS pickup_month,
    COUNT(*) AS trip_count
FROM
    read_parquet(
        [
            's3://prod/yellow_tripdata/*/01/data.parquet',
            's3://prod/yellow_tripdata/*/02/data.parquet',
            's3://prod/yellow_tripdata/*/12/data.parquet'
        ]
    )
WHERE
    1=1
    AND tpep_pickup_datetime BETWEEN '2020-01-01' AND '2026-01-01'
GROUP BY
    1, 2
ORDER BY
    1, 2

   pickup_year pickup_month  trip_count
0   2020-01-01   2020-01-01     6405027
1   2020-01-01   2020-02-01     6299094
2   2020-01-01   2020-03-01          33
3   2020-01-01   2020-04-01           6
4   2020-01-01   2020-05-01          11
5   2020-01-01   2020-06-01           1
6   2020-01-01   2020-07-01           8
7   2020-01-01   2020-11-01          14
8   2020-01-01   2020-12-01     1461879
9   2021-01-01   2021-01-01     1369760
10  2021-01-01   2021-02-01     1371686
11  2021-01-01   2021-03-01           2
12  2021-01-01   2021-04-01           3
13  2021-01-01   2021-05-01           2
14  2021-01-01   2021-06-01           1
15  2021-01-01   2021-11-01          54
16  2021-01-01   2021-12-01     3214285
17  2022-01-01   2022-01-01     2463923
18  2022-01-01   2022-02-01     2979379
19  2022-01-01   2022-03-01          22
20  2022-01-01   2022-04-01          11
21  2022-01-01   2022-05-01           8
22  2022-01-01   2022-10-01          11
23  2022-01-01   2022-11-01          41
24  2022-01-01   2022-12-01     3399528
25  2023-01-01   2023-01-01     3066731
26  2023-01-01   2023-02-01     2913910
27  2023-01-01   2023-03-01          42
28  2023-01-01   2023-11-01          34
29  2023-01-01   2023-12-01     3376534
30  2024-01-01   2024-01-01     2964623
31  2024-01-01   2024-02-01     3007514
32  2024-01-01   2024-03-01           2
33  2024-01-01   2024-11-01          26
34  2024-01-01   2024-12-01     3668358
35  2025-01-01   2025-01-01     3475236
36  2025-01-01   2025-02-01     3577514
37  2025-01-01   2025-03-01           3
38  2025-01-01   2025-11-01           9
39  2025-01-01   2025-12-01     4304997

In [6]:
%%sql
INSTALL fakeit FROM community;
LOAD fakeit;

CREATE OR REPLACE TABLE fake_data AS
SELECT
    s.id AS id,
    fakeit_name_full() AS name,
    fakeit_contact_email() AS email,
    fakeit_address_city() AS city,
    fakeit_address_country() AS country
FROM
    generate_series(1, 100) AS s(id);

Empty DataFrame
Columns: [Success]
Index: []

In [7]:
%%sql
SELECT *
FROM fake_data
LIMIT 5

,id,name,email,city,country
0,1,Marjolaine Muller,angelitadaniel@dicki.name,Toyhaven,Zambia
1,2,Gene Macejkovic,ralphwalsh@stracke.info,Marcusville,Belgium
2,3,Adell Stark,eleonorestanton@rogahn.org,Mannmouth,French Southern Territories
3,4,Lee Harber,quinnheathcote@schmitt.biz,Lucienneview,Fiji
4,5,Kaelyn Block,ameliemoen@toy.org,Waelchiborough,Malawi